project:
  type: website

website:
  title: "Jayitha Cherapanamjeri"
  navbar:
    right:
      - paper-summaries.qmd
      - notes.qmd
      - icon: github
        href: https://github.com/jayitha
      - icon: twitter
        href: https://twitter.com/jayitha4
format:
  html:
    theme: 
      - cyborg
      #- default
      - custom.scss
    css: styles.css

execute:
  freeze: auto



